USE [dswPTP]
GO

/****** Object:  Table [dbo].[stEllipse_MM_MSF170]    Script Date: 15/12/2017 2:16:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stEllipse_MM_MSF170](
	[zSource] [nvarchar](50) NULL,
	[zKey] [nvarchar](63) NULL,
	[DSTRCT_CODE] [nvarchar](4) NULL,
	[STOCK_CODE] [nvarchar](9) NULL,
	[SOH] [decimal](22, 0) NULL,
	[IN_TRANSIT] [decimal](22, 0) NULL,
	[CONSIGN_SOH] [decimal](22, 0) NULL,
	[CONSIGN_ITRANS] [decimal](22, 0) NULL,
	[ROQ] [decimal](22, 0) NULL,
	[DUES_IN] [decimal](22, 0) NULL,
	[LOANS_DUE_BACK] [decimal](22, 0) NULL,
	[LOANS_DUE_OUT] [decimal](22, 0) NULL,
	[DUES_OUT] [decimal](22, 0) NULL,
	[TOTAL_PICKED] [decimal](22, 0) NULL,
	[RESERVED] [decimal](22, 0) NULL,
	[XFERS_REQUEST] [decimal](22, 0) NULL,
	[XFERS_IN_TRANS] [decimal](22, 0) NULL,
	[XFERS_CON_IT] [decimal](22, 0) NULL,
	[CONSIGN_WS_IND] [nvarchar](1) NULL,
	[CLASS] [nvarchar](1) NULL,
	[STOCK_TYPE] [nvarchar](1) NULL,
	[STK_REVIEWER] [nvarchar](10) NULL,
	[STK_REV_DATE] [nvarchar](8) NULL,
	[INVT_CONTROLLR] [nvarchar](10) NULL,
	[INVT_CTL_DATE] [nvarchar](8) NULL,
	[TECH_REVIEWER] [nvarchar](10) NULL,
	[TECH_REV_DATE] [nvarchar](8) NULL,
	[FPA_REC_TYPE] [nvarchar](1) NULL,
	[FPA_ID] [nvarchar](8) NULL,
	[FPA_ITEM_NO] [nvarchar](4) NULL,
	[STOCK_QUALX1] [nvarchar](2) NULL,
	[STOCK_QUALX2] [nvarchar](2) NULL,
	[STOCK_QUALX3] [nvarchar](2) NULL,
	[STOCK_QUALX4] [nvarchar](2) NULL,
	[STOCK_QUALX5] [nvarchar](2) NULL,
	[STOCK_QUALX6] [nvarchar](2) NULL,
	[STOCK_QUALX7] [nvarchar](2) NULL,
	[STOCK_QUALX8] [nvarchar](2) NULL,
	[STOCK_QUALX9] [nvarchar](2) NULL,
	[STOCK_QUALX10] [nvarchar](2) NULL,
	[TAX_CODE] [nvarchar](1) NULL,
	[TAX_PERCENT] [decimal](22, 2) NULL,
	[INVENT_COSTING] [nvarchar](1) NULL,
	[EXP_ELEMENT] [nvarchar](8) NULL,
	[HOME_WHOUSE] [nvarchar](4) NULL,
	[NO_OF_WHOUSES] [nvarchar](3) NULL,
	[NO_OF_LOCAL] [nvarchar](3) NULL,
	[FREIGHT_CHGE] [nvarchar](1) NULL,
	[FREIGHT_PC] [decimal](22, 2) NULL,
	[ABCD_LEVEL] [nvarchar](1) NULL,
	[XYZ_LEVEL] [nvarchar](1) NULL,
	[MSB178_RUN_NO] [nvarchar](4) NULL,
	[PRICE_INDEX] [decimal](22, 0) NULL,
	[ABS_CATEGORY] [nvarchar](8) NULL,
	[ABS_INDEX] [decimal](22, 0) NULL,
	[INVENT_VALUE] [decimal](22, 2) NULL,
	[INVENT_COST_PR] [decimal](22, 6) NULL,
	[UNIT_OF_ISSUE] [nvarchar](4) NULL,
	[LAST_ISS_DATE] [nvarchar](8) NULL,
	[LAST_REC_DATE] [nvarchar](8) NULL,
	[ACTIVITY_CTR] [nvarchar](3) NULL,
	[RAF] [nvarchar](2) NULL,
	[ROP] [decimal](22, 0) NULL,
	[REORDER_QTY] [decimal](22, 0) NULL,
	[MIN_STOCK_LVL] [decimal](22, 0) NULL,
	[PLANNED_SLEVEL] [decimal](22, 2) NULL,
	[INVENTORY_FLAG] [nvarchar](1) NULL,
	[PURCH_FLAG] [nvarchar](1) NULL,
	[PURCH_OFFICER] [nvarchar](10) NULL,
	[PURCH_TRANS] [nvarchar](1) NULL,
	[PRICE_EFF_DATE] [nvarchar](8) NULL,
	[PRICE_EXP_DATE] [nvarchar](8) NULL,
	[CURR_SUPPLIER] [nvarchar](6) NULL,
	[PRICE_CODE] [nvarchar](2) NULL,
	[EXPEDITE_CODE] [nvarchar](2) NULL,
	[ROP_ROQ_UPDATE] [nvarchar](1) NULL,
	[MIN_STK_UPDATE] [nvarchar](1) NULL,
	[REC_ORD_ONLINE] [nvarchar](1) NULL,
	[EQUIP_TRACE_IND] [nvarchar](1) NULL,
	[QUAL_INSP] [nvarchar](2) NULL,
	[SHELF_LIFE] [decimal](22, 0) NULL,
	[STOCK_AT_BIN] [nvarchar](1) NULL,
	[LAST_MOD_DATE] [nvarchar](8) NULL,
	[LAST_MOD_TIME] [nvarchar](6) NULL,
	[LAST_MOD_USER] [nvarchar](10) NULL,
	[CREATION_DATE] [nvarchar](8) NULL,
	[ALPHA_FACTOR] [decimal](22, 2) NULL,
	[SMOOTHING_FLAGX1] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX2] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX3] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX4] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX5] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX6] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX7] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX8] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX9] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX10] [nvarchar](2) NULL,
	[PLANNED_T_OVER] [decimal](22, 2) NULL,
	[STK_RUN_NO] [nvarchar](3) NULL,
	[NXT_STAKE_DATE] [nvarchar](8) NULL,
	[LST_STAKE_DATE] [nvarchar](8) NULL,
	[STAKE_CLASS] [nvarchar](1) NULL,
	[INVT_STAT_CODE] [nvarchar](6) NULL,
	[RESTRICT_POS] [nvarchar](10) NULL,
	[RESTRICT_RULE] [nvarchar](1) NULL,
	[REQ_AUTH_POS] [nvarchar](10) NULL,
	[FRT_IN_INVT] [decimal](22, 2) NULL,
	[CUST_IN_INVT] [decimal](22, 2) NULL,
	[INVENT_PRICE_S] [decimal](22, 6) NULL,
	[FRT_IN_INVT_S] [decimal](22, 2) NULL,
	[CUST_IN_INVT_S] [decimal](22, 2) NULL,
	[TARIFF_CODE] [nvarchar](18) NULL,
	[ORIGIN_CODE] [nvarchar](2) NULL,
	[CUST_CAT_CODE] [nvarchar](10) NULL,
	[INVENT_VALUE_S] [decimal](22, 2) NULL,
	[FRT_IN_I_PRICE] [decimal](22, 6) NULL,
	[FRT_IN_I_PRICE_S] [decimal](22, 6) NULL,
	[CUST_IN_I_PRICE] [decimal](22, 6) NULL,
	[CUST_IN_I_PRICE_S] [decimal](22, 6) NULL,
	[STORES_SALE_PRICE] [decimal](22, 4) NULL,
	[CTAX_CODE] [nvarchar](2) NULL,
	[CATEG_MGT_FLG] [nvarchar](1) NULL,
	[BIN_LABEL_CODE] [nvarchar](2) NULL,
	[REPAIR_FLAG] [nvarchar](1) NULL,
	[AUTO_ORDER_FLG] [nvarchar](1) NULL,
	[AUTO_SHIP_FLG] [nvarchar](1) NULL,
	[REP_SHIP_PRT] [nvarchar](2) NULL,
	[REP_SHIP_POS] [nvarchar](10) NULL,
	[REPAIR_MANAGER] [nvarchar](10) NULL,
	[REPAIR_EXP_ELE] [nvarchar](8) NULL,
	[REP_AGMT_ID] [nvarchar](8) NULL,
	[REP_AGMT_ITEM_NO] [nvarchar](4) NULL,
	[PREV_CURR_SUPP] [nvarchar](6) NULL,
	[DIST_SRCH_FLAG] [nvarchar](1) NULL,
	[INV_REV_DAYS] [nvarchar](4) NULL,
	[PUR_REV_DAYS] [nvarchar](4) NULL,
	[ISS_ONCST_TYPE] [nvarchar](2) NULL,
	[ISS_ONCST_RATE] [decimal](22, 2) NULL,
	[RET_ONCST_TYPE] [nvarchar](2) NULL,
	[RET_ONCST_RATE] [decimal](22, 2) NULL,
	[CAT_COST_SW] [nvarchar](1) NULL,
	[PRIMARY_CAT] [nvarchar](2) NULL,
	[PRIMARY_REP_CAT] [nvarchar](2) NULL,
	[FIXED_ASSET_NO] [nvarchar](12) NULL,
	[SUB_ASSET_NO] [nvarchar](3) NULL,
	[PROJ_WO_NO] [nvarchar](8) NULL,
	[PROJ_WO_IND] [nvarchar](1) NULL,
	[PROJ_WO_EE] [nvarchar](8) NULL,
	[DIRECT_ORDER_IND] [nvarchar](1) NULL,
	[CHARGE_OUT_RATE] [decimal](22, 4) NULL,
	[CHARGE_OUT_RATE_S] [decimal](22, 4) NULL,
	[CPR_CTGY] [nvarchar](4) NULL,
	[CPR_LOCN] [nvarchar](4) NULL,
	[zActive] [bit] NULL,
	[zParentActive] [bit] NULL,
	[zHasInventory] [bit] NULL,
	[zInactiveDistrict] [bit] NULL,
	[zActiveDistrict] [bit] NULL,
	[zRecentMovement] [bit] NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[stEllipse_MSF100]    Script Date: 15/12/2017 2:16:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stEllipse_MSF100](
	[zSource] [nvarchar](50) NULL,
	[STOCK_CODE] [nvarchar](9) NULL,
	[GROUP_CODE] [nvarchar](2) NULL,
	[CLASS_CODE] [nvarchar](2) NULL,
	[STOCK_SECTIONX1] [nvarchar](2) NULL,
	[STOCK_SECTIONX2] [nvarchar](2) NULL,
	[STOCK_SECTIONX3] [nvarchar](2) NULL,
	[STOCK_SECTIONX4] [nvarchar](2) NULL,
	[STOCK_SECTIONX5] [nvarchar](2) NULL,
	[STOCK_SECTIONX6] [nvarchar](2) NULL,
	[STOCK_SECTIONX7] [nvarchar](2) NULL,
	[STOCK_SECTIONX8] [nvarchar](2) NULL,
	[STOCK_SECTIONX9] [nvarchar](2) NULL,
	[STOCK_SECTIONX10] [nvarchar](2) NULL,
	[CLASS] [nvarchar](1) NULL,
	[STOCK_TYPE] [nvarchar](1) NULL,
	[UNIT_OF_ISSUE] [nvarchar](4) NULL,
	[WEIGHT] [decimal](22, 3) NULL,
	[VOLUME] [decimal](22, 6) NULL,
	[UN_TRANSP_CODE] [nvarchar](4) NULL,
	[HAZARD_MAT] [nvarchar](4) NULL,
	[NEW_STK_REQ] [nvarchar](6) NULL,
	[LAST_MOD_DATE] [nvarchar](8) NULL,
	[LAST_MOD_TIME] [nvarchar](6) NULL,
	[LAST_MOD_USER] [nvarchar](10) NULL,
	[CREATION_DATE] [nvarchar](8) NULL,
	[AMEND_NO] [nvarchar](6) NULL,
	[ITEM_NAME_CODE] [nvarchar](5) NULL,
	[ITEM_NAME_SECTOR] [nvarchar](4) NULL,
	[ITEM_NAME] [nvarchar](40) NULL,
	[DESC_LINEX1] [nvarchar](40) NULL,
	[DESC_LINEX2] [nvarchar](40) NULL,
	[DESC_LINEX3] [nvarchar](40) NULL,
	[DESC_LINEX4] [nvarchar](40) NULL,
	[PURCH_TRANS_IND] [nvarchar](1) NULL,
	[EXT_DESC_IND] [nvarchar](1) NULL,
	[NO_OF_INC_LINES] [nvarchar](1) NULL,
	[TRACKING_IND] [nvarchar](1) NULL,
	[STK_ITM_GRP_CD] [nvarchar](9) NULL,
	[ENTITLE_FLAG] [nvarchar](1) NULL,
	[MAX_ENTITLE_QTY] [decimal](22, 0) NULL,
	[REPAIR_FLAG] [nvarchar](1) NULL,
	[AUTO_ORDER_FLG] [nvarchar](1) NULL,
	[AUTO_SHIP_FLG] [nvarchar](1) NULL,
	[TARIFF_CODE] [nvarchar](18) NULL,
	[ORIGIN_CODE] [nvarchar](2) NULL,
	[CONC_CAT_CODE] [nvarchar](10) NULL,
	[zActive] [bit] NULL,
	[zObsolete] [bit] NULL,
	[zOnOrder] [bit] NULL,
	[zInformal] [bit] NULL,
	[zHasInventoryBalance] [bit] NULL,
	[zNotInActiveDistrict] [bit] NULL,
	[zCreatedRecently] [bit] NULL,
	[zActiveDistrict] [bit] NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[stEllipse_MSF170]    Script Date: 15/12/2017 2:16:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stEllipse_MSF170](
	[zSource] [nvarchar](50) NULL,
	[zKey] [nvarchar](63) NULL,
	[DSTRCT_CODE] [nvarchar](4) NULL,
	[STOCK_CODE] [nvarchar](9) NULL,
	[SOH] [decimal](22, 0) NULL,
	[IN_TRANSIT] [decimal](22, 0) NULL,
	[CONSIGN_SOH] [decimal](22, 0) NULL,
	[CONSIGN_ITRANS] [decimal](22, 0) NULL,
	[ROQ] [decimal](22, 0) NULL,
	[DUES_IN] [decimal](22, 0) NULL,
	[LOANS_DUE_BACK] [decimal](22, 0) NULL,
	[LOANS_DUE_OUT] [decimal](22, 0) NULL,
	[DUES_OUT] [decimal](22, 0) NULL,
	[TOTAL_PICKED] [decimal](22, 0) NULL,
	[RESERVED] [decimal](22, 0) NULL,
	[XFERS_REQUEST] [decimal](22, 0) NULL,
	[XFERS_IN_TRANS] [decimal](22, 0) NULL,
	[XFERS_CON_IT] [decimal](22, 0) NULL,
	[CONSIGN_WS_IND] [nvarchar](1) NULL,
	[CLASS] [nvarchar](1) NULL,
	[STOCK_TYPE] [nvarchar](1) NULL,
	[STK_REVIEWER] [nvarchar](10) NULL,
	[STK_REV_DATE] [nvarchar](8) NULL,
	[INVT_CONTROLLR] [nvarchar](10) NULL,
	[INVT_CTL_DATE] [nvarchar](8) NULL,
	[TECH_REVIEWER] [nvarchar](10) NULL,
	[TECH_REV_DATE] [nvarchar](8) NULL,
	[FPA_REC_TYPE] [nvarchar](1) NULL,
	[FPA_ID] [nvarchar](8) NULL,
	[FPA_ITEM_NO] [nvarchar](4) NULL,
	[STOCK_QUALX1] [nvarchar](2) NULL,
	[STOCK_QUALX2] [nvarchar](2) NULL,
	[STOCK_QUALX3] [nvarchar](2) NULL,
	[STOCK_QUALX4] [nvarchar](2) NULL,
	[STOCK_QUALX5] [nvarchar](2) NULL,
	[STOCK_QUALX6] [nvarchar](2) NULL,
	[STOCK_QUALX7] [nvarchar](2) NULL,
	[STOCK_QUALX8] [nvarchar](2) NULL,
	[STOCK_QUALX9] [nvarchar](2) NULL,
	[STOCK_QUALX10] [nvarchar](2) NULL,
	[TAX_CODE] [nvarchar](1) NULL,
	[TAX_PERCENT] [decimal](22, 2) NULL,
	[INVENT_COSTING] [nvarchar](1) NULL,
	[EXP_ELEMENT] [nvarchar](8) NULL,
	[HOME_WHOUSE] [nvarchar](4) NULL,
	[NO_OF_WHOUSES] [nvarchar](3) NULL,
	[NO_OF_LOCAL] [nvarchar](3) NULL,
	[FREIGHT_CHGE] [nvarchar](1) NULL,
	[FREIGHT_PC] [decimal](22, 2) NULL,
	[ABCD_LEVEL] [nvarchar](1) NULL,
	[XYZ_LEVEL] [nvarchar](1) NULL,
	[MSB178_RUN_NO] [nvarchar](4) NULL,
	[PRICE_INDEX] [decimal](22, 0) NULL,
	[ABS_CATEGORY] [nvarchar](8) NULL,
	[ABS_INDEX] [decimal](22, 0) NULL,
	[INVENT_VALUE] [decimal](22, 2) NULL,
	[INVENT_COST_PR] [decimal](22, 6) NULL,
	[UNIT_OF_ISSUE] [nvarchar](4) NULL,
	[LAST_ISS_DATE] [nvarchar](8) NULL,
	[LAST_REC_DATE] [nvarchar](8) NULL,
	[ACTIVITY_CTR] [nvarchar](3) NULL,
	[RAF] [nvarchar](2) NULL,
	[ROP] [decimal](22, 0) NULL,
	[REORDER_QTY] [decimal](22, 0) NULL,
	[MIN_STOCK_LVL] [decimal](22, 0) NULL,
	[PLANNED_SLEVEL] [decimal](22, 2) NULL,
	[INVENTORY_FLAG] [nvarchar](1) NULL,
	[PURCH_FLAG] [nvarchar](1) NULL,
	[PURCH_OFFICER] [nvarchar](10) NULL,
	[PURCH_TRANS] [nvarchar](1) NULL,
	[PRICE_EFF_DATE] [nvarchar](8) NULL,
	[PRICE_EXP_DATE] [nvarchar](8) NULL,
	[CURR_SUPPLIER] [nvarchar](6) NULL,
	[PRICE_CODE] [nvarchar](2) NULL,
	[EXPEDITE_CODE] [nvarchar](2) NULL,
	[ROP_ROQ_UPDATE] [nvarchar](1) NULL,
	[MIN_STK_UPDATE] [nvarchar](1) NULL,
	[REC_ORD_ONLINE] [nvarchar](1) NULL,
	[EQUIP_TRACE_IND] [nvarchar](1) NULL,
	[QUAL_INSP] [nvarchar](2) NULL,
	[SHELF_LIFE] [decimal](22, 0) NULL,
	[STOCK_AT_BIN] [nvarchar](1) NULL,
	[LAST_MOD_DATE] [nvarchar](8) NULL,
	[LAST_MOD_TIME] [nvarchar](6) NULL,
	[LAST_MOD_USER] [nvarchar](10) NULL,
	[CREATION_DATE] [nvarchar](8) NULL,
	[ALPHA_FACTOR] [decimal](22, 2) NULL,
	[SMOOTHING_FLAGX1] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX2] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX3] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX4] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX5] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX6] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX7] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX8] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX9] [nvarchar](2) NULL,
	[SMOOTHING_FLAGX10] [nvarchar](2) NULL,
	[PLANNED_T_OVER] [decimal](22, 2) NULL,
	[STK_RUN_NO] [nvarchar](3) NULL,
	[NXT_STAKE_DATE] [nvarchar](8) NULL,
	[LST_STAKE_DATE] [nvarchar](8) NULL,
	[STAKE_CLASS] [nvarchar](1) NULL,
	[INVT_STAT_CODE] [nvarchar](6) NULL,
	[RESTRICT_POS] [nvarchar](10) NULL,
	[RESTRICT_RULE] [nvarchar](1) NULL,
	[REQ_AUTH_POS] [nvarchar](10) NULL,
	[FRT_IN_INVT] [decimal](22, 2) NULL,
	[CUST_IN_INVT] [decimal](22, 2) NULL,
	[INVENT_PRICE_S] [decimal](22, 6) NULL,
	[FRT_IN_INVT_S] [decimal](22, 2) NULL,
	[CUST_IN_INVT_S] [decimal](22, 2) NULL,
	[TARIFF_CODE] [nvarchar](18) NULL,
	[ORIGIN_CODE] [nvarchar](2) NULL,
	[CUST_CAT_CODE] [nvarchar](10) NULL,
	[INVENT_VALUE_S] [decimal](22, 2) NULL,
	[FRT_IN_I_PRICE] [decimal](22, 6) NULL,
	[FRT_IN_I_PRICE_S] [decimal](22, 6) NULL,
	[CUST_IN_I_PRICE] [decimal](22, 6) NULL,
	[CUST_IN_I_PRICE_S] [decimal](22, 6) NULL,
	[STORES_SALE_PRICE] [decimal](22, 4) NULL,
	[CTAX_CODE] [nvarchar](2) NULL,
	[CATEG_MGT_FLG] [nvarchar](1) NULL,
	[BIN_LABEL_CODE] [nvarchar](2) NULL,
	[REPAIR_FLAG] [nvarchar](1) NULL,
	[AUTO_ORDER_FLG] [nvarchar](1) NULL,
	[AUTO_SHIP_FLG] [nvarchar](1) NULL,
	[REP_SHIP_PRT] [nvarchar](2) NULL,
	[REP_SHIP_POS] [nvarchar](10) NULL,
	[REPAIR_MANAGER] [nvarchar](10) NULL,
	[REPAIR_EXP_ELE] [nvarchar](8) NULL,
	[REP_AGMT_ID] [nvarchar](8) NULL,
	[REP_AGMT_ITEM_NO] [nvarchar](4) NULL,
	[PREV_CURR_SUPP] [nvarchar](6) NULL,
	[DIST_SRCH_FLAG] [nvarchar](1) NULL,
	[INV_REV_DAYS] [nvarchar](4) NULL,
	[PUR_REV_DAYS] [nvarchar](4) NULL,
	[ISS_ONCST_TYPE] [nvarchar](2) NULL,
	[ISS_ONCST_RATE] [decimal](22, 2) NULL,
	[RET_ONCST_TYPE] [nvarchar](2) NULL,
	[RET_ONCST_RATE] [decimal](22, 2) NULL,
	[CAT_COST_SW] [nvarchar](1) NULL,
	[PRIMARY_CAT] [nvarchar](2) NULL,
	[PRIMARY_REP_CAT] [nvarchar](2) NULL,
	[FIXED_ASSET_NO] [nvarchar](12) NULL,
	[SUB_ASSET_NO] [nvarchar](3) NULL,
	[PROJ_WO_NO] [nvarchar](8) NULL,
	[PROJ_WO_IND] [nvarchar](1) NULL,
	[PROJ_WO_EE] [nvarchar](8) NULL,
	[DIRECT_ORDER_IND] [nvarchar](1) NULL,
	[CHARGE_OUT_RATE] [decimal](22, 4) NULL,
	[CHARGE_OUT_RATE_S] [decimal](22, 4) NULL,
	[CPR_CTGY] [nvarchar](4) NULL,
	[CPR_LOCN] [nvarchar](4) NULL,
	[zActive] [bit] NULL,
	[zParentActive] [bit] NULL,
	[zHasInventory] [bit] NULL,
	[zInactiveDistrict] [bit] NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[stEllipse_MSF200]    Script Date: 15/12/2017 2:16:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stEllipse_MSF200](
	[zSource] [nvarchar](50) NULL,
	[SUPPLIER_NO] [nvarchar](6) NULL,
	[SUP_STATUS] [nvarchar](1) NULL,
	[SUPPLIER_NAME] [nvarchar](32) NULL,
	[ORDER_ADDR_1] [nvarchar](32) NULL,
	[ORDER_ADDR_2] [nvarchar](32) NULL,
	[ORDER_ADDR_3] [nvarchar](32) NULL,
	[ORDER_ZIP] [nvarchar](10) NULL,
	[ORDER_PHONE] [nvarchar](16) NULL,
	[ORDER_CONTACT] [nvarchar](32) NULL,
	[ORDER_STATE] [nvarchar](2) NULL,
	[ORDER_FAX_NO] [nvarchar](16) NULL,
	[ORDER_TLX_NAME] [nvarchar](32) NULL,
	[ORDER_TLX_NO] [nvarchar](22) NULL,
	[PAYMENT_NAME] [nvarchar](32) NULL,
	[PAYMENT_ADDR_1] [nvarchar](32) NULL,
	[PAYMENT_ADDR_2] [nvarchar](32) NULL,
	[PAYMENT_ADDR_3] [nvarchar](32) NULL,
	[PAYMENT_ZIP] [nvarchar](10) NULL,
	[PAYMENT_PHONE] [nvarchar](16) NULL,
	[PAYMENT_CTACT] [nvarchar](32) NULL,
	[PAYMENT_STATE] [nvarchar](2) NULL,
	[PAY_FAX_NO] [nvarchar](16) NULL,
	[PAY_TLX_NAME] [nvarchar](32) NULL,
	[PAY_TLX_NO] [nvarchar](22) NULL,
	[PAYMENT_LINK] [nvarchar](6) NULL,
	[RETURNS_NAME] [nvarchar](32) NULL,
	[RETURNS_ADDR_1] [nvarchar](32) NULL,
	[RETURNS_ADDR_2] [nvarchar](32) NULL,
	[RETURNS_ADDR_3] [nvarchar](32) NULL,
	[RETURNS_ZIP] [nvarchar](10) NULL,
	[RETURNS_PHONE] [nvarchar](16) NULL,
	[RETURNS_CTACT] [nvarchar](32) NULL,
	[RETURNS_STATE] [nvarchar](2) NULL,
	[RETURNS_FAX_NO] [nvarchar](16) NULL,
	[RETS_TLX_NAME] [nvarchar](32) NULL,
	[RETS_TLX_NO] [nvarchar](22) NULL,
	[CLOSE_XMAS] [nvarchar](1) NULL,
	[CLOSE_XMAS_ST] [nvarchar](8) NULL,
	[CLOSE_XMAS_END] [nvarchar](8) NULL,
	[NO_ITEM_ORDER] [nvarchar](1) NULL,
	[FRT_IN_DISC] [nvarchar](1) NULL,
	[SEP_CHEQUE] [nvarchar](1) NULL,
	[LINKED_SUPP_NO] [nvarchar](6) NULL,
	[LINKED_CUST_NO] [nvarchar](6) NULL,
	[COUNTRY_CODE] [nvarchar](3) NULL,
	[SUP_TYPEX1] [nvarchar](2) NULL,
	[SUP_TYPEX2] [nvarchar](2) NULL,
	[SUP_TYPEX3] [nvarchar](2) NULL,
	[SUP_TYPEX4] [nvarchar](2) NULL,
	[SUP_TYPEX5] [nvarchar](2) NULL,
	[SUP_TYPEX6] [nvarchar](2) NULL,
	[PAY_CONTRA] [nvarchar](1) NULL,
	[CURRENCY_TYPE] [nvarchar](4) NULL,
	[LAST_MOD_DATE] [nvarchar](8) NULL,
	[LAST_MOD_TIME] [nvarchar](6) NULL,
	[LAST_MOD_USER] [nvarchar](10) NULL,
	[CREATION_DATE] [nvarchar](8) NULL,
	[CREATION_TIME] [nvarchar](6) NULL,
	[CREATION_USER] [nvarchar](10) NULL,
	[COMMODITY_TYX1] [nvarchar](4) NULL,
	[COMMODITY_TYX2] [nvarchar](4) NULL,
	[COMMODITY_TYX3] [nvarchar](4) NULL,
	[COMMODITY_TYX4] [nvarchar](4) NULL,
	[COMMODITY_TYX5] [nvarchar](4) NULL,
	[COMMODITY_TYX6] [nvarchar](4) NULL,
	[EMAIL_ADDRESS] [nvarchar](40) NULL,
	[zActive] [bit] NULL,
	[zCurrentPO] [bit] NULL,
	[zStatusActive] [bit] NULL,
	[zActiveDistrict] [bit] NULL,
	[zCreatedRecently] [bit] NULL,
	[zCurrentAP] [bit] NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[stEllipse_MSF203]    Script Date: 15/12/2017 2:16:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stEllipse_MSF203](
	[zSource] [nvarchar](50) NULL,
	[zKey] [nvarchar](60) NULL,
	[DSTRCT_CODE] [nvarchar](4) NULL,
	[SUPPLIER_NO] [nvarchar](6) NULL,
	[SUP_STATUS] [nvarchar](1) NULL,
	[ACCOUNT_NO] [nvarchar](10) NULL,
	[NO_OF_DAYS_PAY] [nvarchar](2) NULL,
	[INV_STMT_IND] [nvarchar](1) NULL,
	[STMT_CLOSE_DAY] [nvarchar](2) NULL,
	[SETTLE_DISC] [decimal](22, 2) NULL,
	[SETTLE_DAYS] [nvarchar](2) NULL,
	[SET_DISC_FLAG] [nvarchar](1) NULL,
	[RECON_REQUIRED] [nvarchar](1) NULL,
	[ORDS_ALLOWED] [nvarchar](1) NULL,
	[PAYMNT_ALLOWED] [nvarchar](1) NULL,
	[DELIV_LOCATION] [nvarchar](4) NULL,
	[MINIMUM_ORDER] [decimal](22, 2) NULL,
	[FRT_IN_DISC] [nvarchar](1) NULL,
	[TEN99_YN] [nvarchar](1) NULL,
	[TEN99_ID] [nvarchar](11) NULL,
	[TEN99_TYPE] [nvarchar](1) NULL,
	[COUNTY] [nvarchar](2) NULL,
	[INSTATE_IND] [nvarchar](1) NULL,
	[EEOC_CODE] [nvarchar](1) NULL,
	[MAX_ORD_ITEMS] [decimal](22, 0) NULL,
	[WHOLD_TAX_CODE] [nvarchar](2) NULL,
	[HDR_ATAX_CODE] [nvarchar](4) NULL,
	[ITM_ATAX_CODE] [nvarchar](4) NULL,
	[TAX_FILE_NO] [nvarchar](14) NULL,
	[EXMPT_CERT_NO] [nvarchar](11) NULL,
	[EXMPT_STR_DATE] [nvarchar](8) NULL,
	[EXMPT_END_DATE] [nvarchar](8) NULL,
	[DELIV_PERF_RTE] [decimal](22, 0) NULL,
	[BANK_ACCT_NAME] [nvarchar](40) NULL,
	[BANK_ACCT_NO] [nvarchar](20) NULL,
	[BANK_ACCT_TY] [nvarchar](1) NULL,
	[BRANCH_CODE] [nvarchar](15) NULL,
	[DEF_BANK_ACCT_NAME] [nvarchar](40) NULL,
	[DEF_BANK_ACCT_NO] [nvarchar](20) NULL,
	[DEF_BRANCH_CODE] [nvarchar](15) NULL,
	[LAST_MOD_DATE] [nvarchar](8) NULL,
	[LAST_MOD_TIME] [nvarchar](6) NULL,
	[LAST_MOD_USER] [nvarchar](10) NULL,
	[CREATION_DATE] [nvarchar](8) NULL,
	[CREATION_TIME] [nvarchar](6) NULL,
	[CREATION_USER] [nvarchar](10) NULL,
	[EXEMPTION_TYPE] [nvarchar](1) NULL,
	[ORD_MEDIUM_IND] [nvarchar](1) NULL,
	[PAYMENT_METH_IND] [nvarchar](1) NULL,
	[AUTO_INV_IND] [nvarchar](1) NULL,
	[AUTO_INV_PREF] [nvarchar](2) NULL,
	[LST_AUTOINV_NO] [nvarchar](8) NULL,
	[AI_MEDIUM_IND] [nvarchar](1) NULL,
	[FRT_DEFAULT] [nvarchar](2) NULL,
	[REMIT_MEDIUM_IND] [nvarchar](1) NULL,
	[RFQ_MEDIUM_IND] [nvarchar](1) NULL,
	[HANDLE_CDE] [nvarchar](2) NULL,
	[EFT_MEDIUM_IND] [nvarchar](1) NULL,
	[TAX_REG_NO] [nvarchar](20) NULL,
	[LAST_WH_CERT_NO] [nvarchar](8) NULL,
	[zActive] [bit] NULL,
	[zStatusActive] [bit] NULL,
	[zCurrentPO] [bit] NULL,
	[zCreatedRecently] [bit] NULL,
	[zCurrentAP] [bit] NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[stEllipse_MSF221]    Script Date: 15/12/2017 2:16:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stEllipse_MSF221](
	[zSource] [nvarchar](50) NULL,
	[PO_NO] [nvarchar](6) NULL,
	[PO_ITEM_NO] [nvarchar](3) NULL,
	[STATUS_221] [nvarchar](1) NULL,
	[DSTRCT_CODE] [nvarchar](4) NULL,
	[PO_CREATE_IND] [nvarchar](1) NULL,
	[PO_ITEM_TYPE] [nvarchar](1) NULL,
	[PO_ITEM_MEDIUM] [nvarchar](1) NULL,
	[PO_NUMBER_IND] [nvarchar](1) NULL,
	[CHANGE_COUNT] [nvarchar](4) NULL,
	[AUTHSD_STATUS] [nvarchar](1) NULL,
	[AUTHSD_BY] [nvarchar](10) NULL,
	[LAST_PRT_RUNNO] [nvarchar](4) NULL,
	[PO_DESC_IND] [nvarchar](1) NULL,
	[RECEIPT_STATUS] [nvarchar](1) NULL,
	[CURR_DUE_DATE] [nvarchar](8) NULL,
	[SUPP_LEAD_TIME] [nvarchar](4) NULL,
	[DUE_SITE_DATE] [nvarchar](8) NULL,
	[ACT_LEAD_TIME] [nvarchar](4) NULL,
	[PREQ_STK_CODE] [nvarchar](9) NULL,
	[REVSD_CRT_DATE] [nvarchar](8) NULL,
	[UNIT_OF_PURCH] [nvarchar](4) NULL,
	[UNIT_OF_ISSUE] [nvarchar](4) NULL,
	[CONV_FACTOR] [decimal](22, 4) NULL,
	[INSPECT_CODE] [nvarchar](2) NULL,
	[FPA_REC_TYPE] [nvarchar](1) NULL,
	[FPA_GROUP] [nvarchar](5) NULL,
	[FPA_AGREEMENT] [nvarchar](3) NULL,
	[FPA_ITEM_NO] [nvarchar](4) NULL,
	[GPA_ID_ITEM] [nvarchar](11) NULL,
	[GPA_ITEM_NO] [nvarchar](7) NULL,
	[PRICE_CODE] [nvarchar](2) NULL,
	[WHOLD_TAX_CODE] [nvarchar](2) NULL,
	[EDI_ORDER_STATUS] [nvarchar](3) NULL,
	[EDI_ACK_STATUS] [nvarchar](2) NULL,
	[ORIG_DUE_DATE] [nvarchar](8) NULL,
	[ORIG_QTY_I] [decimal](22, 2) NULL,
	[ORIG_NET_PR_I] [decimal](22, 6) NULL,
	[WHOUSE_ID] [nvarchar](4) NULL,
	[CURR_QTY_I] [decimal](22, 2) NULL,
	[CURR_NET_PR_I] [decimal](22, 6) NULL,
	[DISCOUNT_A] [decimal](22, 2) NULL,
	[DISCOUNT_B] [decimal](22, 2) NULL,
	[SETTLE_DAYS_A] [decimal](22, 0) NULL,
	[SETTLE_PC_A] [decimal](22, 2) NULL,
	[SETTLE_DAYS_B] [decimal](22, 0) NULL,
	[SETTLE_PC_B] [decimal](22, 2) NULL,
	[GROSS_PRICE_P] [decimal](22, 4) NULL,
	[CURR_QTY_P] [decimal](22, 2) NULL,
	[CURR_NET_PR_P] [decimal](22, 4) NULL,
	[RETN_QTY_P] [decimal](22, 2) NULL,
	[OFFSET_QTY_I] [decimal](22, 2) NULL,
	[RETN_NETPR_I] [decimal](22, 6) NULL,
	[RETN_NETPR_I_S] [decimal](22, 6) NULL,
	[QTY_INVOICE_P] [decimal](22, 0) NULL,
	[TAX_CODE] [nvarchar](1) NULL,
	[TAX_PERCENT] [decimal](22, 2) NULL,
	[CTAX_CODE] [nvarchar](2) NULL,
	[INDEX_EFF_DATE] [nvarchar](8) NULL,
	[EXPEDITE_CODE] [nvarchar](2) NULL,
	[EXPEDITE_COUNT] [nvarchar](2) NULL,
	[EXPEDITE_ACTN] [nvarchar](2) NULL,
	[EXPEDITE_DATE] [nvarchar](8) NULL,
	[EXPED_RUN_NO] [nvarchar](3) NULL,
	[APPR_QTY_UOP] [decimal](22, 2) NULL,
	[LAST_APPR_DATE] [nvarchar](8) NULL,
	[VAL_APPR] [decimal](22, 2) NULL,
	[INV_QTY_UOP] [decimal](22, 2) NULL,
	[INVOICE_REF] [nvarchar](10) NULL,
	[INV_PEND_QTY_P] [decimal](22, 2) NULL,
	[INV_PEND_VAL_F] [decimal](22, 2) NULL,
	[INV_PEND_VAL_L] [decimal](22, 2) NULL,
	[INV_PEND_VAL_S] [decimal](22, 2) NULL,
	[INV_PEND_TAX_F] [decimal](22, 2) NULL,
	[CTAX_PENDVAL_F] [decimal](22, 2) NULL,
	[CTAX_PENDVAL_L] [decimal](22, 2) NULL,
	[CTAX_PENDVAL_S] [decimal](22, 2) NULL,
	[RETN_APPRVAL_F] [decimal](22, 2) NULL,
	[RETN_APPRVAL_L] [decimal](22, 2) NULL,
	[RETN_APPRVAL_S] [decimal](22, 2) NULL,
	[RETN_CLEAR_F] [decimal](22, 2) NULL,
	[RETN_CLEAR_L] [decimal](22, 2) NULL,
	[RETN_CLEAR_S] [decimal](22, 2) NULL,
	[RETN_OFFSET_F] [decimal](22, 2) NULL,
	[RETN_OFFSET_L] [decimal](22, 2) NULL,
	[RETN_OFFSET_S] [decimal](22, 2) NULL,
	[RETN_PR_VAR_F] [decimal](22, 2) NULL,
	[RETN_PR_VAR_L] [decimal](22, 2) NULL,
	[RETN_PR_VAR_S] [decimal](22, 2) NULL,
	[PREP_APPRVAL_F] [decimal](22, 2) NULL,
	[PREP_APPRVAL_S] [decimal](22, 2) NULL,
	[PREP_APPRVAL_L] [decimal](22, 2) NULL,
	[PREP_CTAXVAL_F] [decimal](22, 2) NULL,
	[PREP_CTAXVAL_L] [decimal](22, 2) NULL,
	[PREP_CTAXVAL_S] [decimal](22, 2) NULL,
	[PREP_VAL_F] [decimal](22, 2) NULL,
	[QTY_RCV_DIR_I] [decimal](22, 2) NULL,
	[QTY_EX_OFST_I] [decimal](22, 2) NULL,
	[ONST_RCPT_DATE] [nvarchar](8) NULL,
	[ONST_RCPT_REF] [nvarchar](10) NULL,
	[CUST_CLEAR_AMT_L] [decimal](22, 2) NULL,
	[CUST_CLEAR_AMT_F] [decimal](22, 2) NULL,
	[CUST_CLEAR_AMT_S] [decimal](22, 2) NULL,
	[VAL_RCPT_FOR] [decimal](22, 2) NULL,
	[VALUE_RCVD_FOR] [decimal](22, 2) NULL,
	[INVENT_CHG_LOC] [decimal](22, 2) NULL,
	[INVENT_CHG_FOR] [decimal](22, 2) NULL,
	[INVENT_CHG_SEC] [decimal](22, 2) NULL,
	[USE_TAX_AMT_L] [decimal](22, 2) NULL,
	[USE_TAX_AMT_F] [decimal](22, 2) NULL,
	[USE_TAX_AMT_S] [decimal](22, 2) NULL,
	[ISS_QTY_ACQUIT] [decimal](22, 0) NULL,
	[IREQ_NO] [nvarchar](6) NULL,
	[IREQ_ITEM] [nvarchar](4) NULL,
	[ORIG_IREQ_IND] [nvarchar](1) NULL,
	[ORIG_IREQ_NO] [nvarchar](6) NULL,
	[ORIG_IREQ_ITEM] [nvarchar](4) NULL,
	[SUPP_DESP_DATE] [nvarchar](8) NULL,
	[TARIFF_CODE] [nvarchar](18) NULL,
	[CONC_CAT_CODE] [nvarchar](10) NULL,
	[LTI_RBTE_VALUE_L] [decimal](22, 2) NULL,
	[LTI_RBTE_VALUE_F] [decimal](22, 2) NULL,
	[LTI_RBTE_VALUE_S] [decimal](22, 2) NULL,
	[STI_RBTE_VALUE_L] [decimal](22, 2) NULL,
	[STI_RBTE_VALUE_F] [decimal](22, 2) NULL,
	[STI_RBTE_VALUE_S] [decimal](22, 2) NULL,
	[OTH_RBTE_VALUE_L] [decimal](22, 2) NULL,
	[OTH_RBTE_VALUE_F] [decimal](22, 2) NULL,
	[OTH_RBTE_VALUE_S] [decimal](22, 2) NULL,
	[SHIPPED_DATE] [nvarchar](8) NULL,
	[SHIPPED_TIME] [nvarchar](6) NULL,
	[AUTO_INV_QTY] [decimal](22, 2) NULL,
	[AUTO_INV_VAL] [decimal](22, 2) NULL,
	[QTY_RCV_OFST_I] [decimal](22, 2) NULL,
	[OFST_RCPT_DATE] [nvarchar](8) NULL,
	[OFST_RCPT_REF] [nvarchar](10) NULL,
	[EXTERNAL_DOC_REF] [nvarchar](15) NULL,
	[ACTIVITY_CTR] [nvarchar](3) NULL,
	[REP_REQ_NO] [nvarchar](8) NULL,
	[REP_REQ_ITEM] [nvarchar](3) NULL,
	[NO_OF_TASKS] [nvarchar](3) NULL,
	[HIGHEST_TASK] [nvarchar](3) NULL,
	[NPVCA_SEC] [decimal](22, 2) NULL,
	[RETN_ORDER_IND] [nvarchar](1) NULL,
	[ORIG_NO] [nvarchar](6) NULL,
	[ORIG_ITEM_NO] [nvarchar](3) NULL,
	[INVENT_CAT] [nvarchar](2) NULL,
	[DELIV_LOCATION] [nvarchar](4) NULL,
	[ORIG_DST_CDE] [nvarchar](4) NULL,
	[AR_INV_VAL] [decimal](22, 2) NULL,
	[TOT_PO_ITEM_VAL] [decimal](22, 2) NULL,
	[EXCH_RATE] [decimal](22, 7) NULL,
	[PRICE_MOD_DATE] [nvarchar](8) NULL,
	[IDT_BTWN_SYS_STAT] [nvarchar](1) NULL,
	[LAST_MOD_DATE] [nvarchar](8) NULL,
	[LAST_MOD_TIME] [nvarchar](6) NULL,
	[LAST_MOD_USER] [nvarchar](10) NULL,
	[zActive] [bit] NULL
) ON [PRIMARY]

GO

/****** Object:  Table [dbo].[ztActive_DSTRCT_CODES]    Script Date: 15/12/2017 2:16:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ztActive_DSTRCT_CODES](
	[zSource] [nvarchar](50) NULL,
	[DSTRCT_CODE] [nvarchar](4) NULL,
	[zComment] [nvarchar](50) NULL
) ON [PRIMARY]

GO


